services:
  redirect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./redirect.conf:/app/redirect.conf
    environment:
      # Add environment variables if needed
      - RUST_LOG=INFO

  nginx:
    image: nginx:latest
    ports:
      - "1024:80" # for rootless
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - redirect
